# Dataset

In [1]:
# Import dataset in two way

In [2]:
# 1st process

In [6]:
DataFrame<-read.csv(file.choose())

In [7]:
#2nd steps from working directory

In [8]:
getwd()   #current working directory

[1] "C:/Users/gazur/Desktop/R_Programming(A-Z)/Lec-05(Data_Frame)"

In [10]:
setwd("C:/Users/gazur/Desktop/R_Programming(A-Z)/Lec-05(Data_Frame)")

In [12]:
rm(DataFrame)

In [14]:
DataFrame <- read.csv('P2-Demographic-Data.csv')

In [17]:
DataFrame.head

ERROR: Error in eval(expr, envir, enclos): object 'DataFrame.head' not found

In [18]:
nrow(DataFrame)

[1] 195

In [19]:
ncol(DataFrame)

[1] 5

In [24]:
head(DataFrame, n=10)

   Country.Name         Country.Code Birth.rate Internet.users
1  Aruba                ABW          10.244     78.9000
2  Afghanistan          AFG          35.253      5.9000
3  Angola               AGO          45.985     19.1000
4  Albania              ALB          12.877     57.2000
5  United Arab Emirates ARE          11.044     88.0000
6  Argentina            ARG          17.716     59.9000
7  Armenia              ARM          13.308     41.9000
8  Antigua and Barbuda  ATG          16.447     63.4000
9  Australia            AUS          13.200     83.0000
10 Austria              AUT           9.400     80.6188
   Income.Group
1  High income
2  Low income
3  Upper middle income
4  Upper middle income
5  High income
6  High income
7  Lower middle income
8  High income
9  High income
10 High income

In [23]:
tail(DataFrame)

    Country.Name     Country.Code Birth.rate Internet.users Income.Group
190 Samoa            WSM          26.172     15.3           Lower middle income
191 Yemen, Rep.      YEM          32.947     20.0           Lower middle income
192 South Africa     ZAF          20.850     46.5           Upper middle income
193 Congo, Dem. Rep. COD          42.394      2.2           Low income
194 Zambia           ZMB          40.471     15.4           Lower middle income
195 Zimbabwe         ZWE          35.715     18.5           Low income

In [25]:
str(DataFrame)        #structure of  Dataset

#runif  #random ditribution r unif like rnorm
#Here Categorical data represent as ''Factor''

'data.frame':	195 obs. of  5 variables:
 $ Country.Name  : Factor w/ 195 levels "Afghanistan",..: 8 1 4 2 183 6 7 5 9 10 ...
 $ Country.Code  : Factor w/ 195 levels "ABW","AFG","AGO",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Birth.rate    : num  10.2 35.3 46 12.9 11 ...
 $ Internet.users: num  78.9 5.9 19.1 57.2 88 ...
 $ Income.Group  : Factor w/ 4 levels "High income",..: 1 2 4 4 1 1 3 1 1 1 ...

In [26]:
 summary(DataFrame)

              Country.Name  Country.Code   Birth.rate    Internet.users
 Afghanistan        :  1   ABW    :  1   Min.   : 7.90   Min.   : 0.90
 Albania            :  1   AFG    :  1   1st Qu.:12.12   1st Qu.:14.52
 Algeria            :  1   AGO    :  1   Median :19.68   Median :41.00
 Angola             :  1   ALB    :  1   Mean   :21.47   Mean   :42.08
 Antigua and Barbuda:  1   ARE    :  1   3rd Qu.:29.76   3rd Qu.:66.22
 Argentina          :  1   ARG    :  1   Max.   :49.66   Max.   :96.55
 (Other)            :189   (Other):189
              Income.Group
 High income        :67
 Low income         :30
 Lower middle income:50
 Upper middle income:48

In [27]:
# select a single row

In [33]:
DataFrame[4,2]

[1] ALB
195 Levels: ABW AFG AGO ALB ARE ARG ARM ATG AUS AUT AZE BDI BEL BEN BFA ... ZWE

In [34]:
DataFrame[4, "Birth.rate"]   datafram row has number and column have name

[1] 12.877